import { initializeApp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-app.js';
import { getFirestore, collection, doc, getDocs, setDoc, addDoc, updateDoc, query, where, limit, serverTimestamp } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-firestore.js';
import { getAuth, signInAnonymously } from 'https://www.gstatic.com/firebasejs/12.15.0/firebase-auth.js';
import { firebaseConfig } from './firebase-config.js';
import { premadeCourses, departments, roles } from './courses.js';

const app=initializeApp(firebaseConfig), db=getFirestore(app), auth=getAuth(app);
const $=id=>document.getElementById(id), today=()=>new Date().toISOString().slice(0,10), uid=p=>`${p}-${Date.now().toString(36)}-${Math.random().toString(36).slice(2,7)}`.toUpperCase();
const esc=v=>String(v??'').replace(/[&<>]/g,s=>({'&':'&amp;','<':'&lt;','>':'&gt;'}[s]));
const state={user:null,route:'dashboard',employees:[],courses:[],assignments:[],progress:[],certifications:[],attempts:[],player:null};
async function hash(t){const b=await crypto.subtle.digest('SHA-256',new TextEncoder().encode(t));return[...new Uint8Array(b)].map(x=>x.toString(16).padStart(2,'0')).join('')}
const admin=()=>['Owner','Executive','Board of Directors'].includes(state.user?.role)||String(state.user?.role||'').startsWith('Chief');
const manager=()=>admin()||/Supervisor|Lead|Officer|Board|Executive|Owner|Chief/.test(state.user?.role||'');
const pill=(t,c='')=>`<span class="pill ${c}">${esc(t)}</span>`;
const modal=html=>{$('modalContent').innerHTML=html;$('modal').classList.remove('hidden')}; window.closeModal=()=>$('modal').classList.add('hidden');

async function init(){try{await signInAnonymously(auth)}catch(e){console.warn('Enable Anonymous Auth in Firebase.')} await checkOwner(); $('setupBtn').onclick=setupOwner; $('loginBtn').onclick=login; $('logoutBtn').onclick=()=>location.reload()}
async function checkOwner(){const s=await getDocs(query(collection(db,'employees'),where('role','==','Owner'),limit(1)));$('ownerSetup').classList.toggle('hidden',!s.empty);$('normalLogin').classList.toggle('hidden',s.empty)}
async function setupOwner(){const pin=$('setupPin').value.trim(),discordId=$('setupDiscordId').value.trim(),username=$('setupUsername').value.trim();if(!discordId||!username||!/^[0-9]{4}$/.test(pin))return notice('Enter Discord ID, username, and a 4-digit PIN.');await setDoc(doc(db,'employees','EMP-000001'),{displayName:$('setupDisplay').value.trim()||'Christopher Shelley',discordUsername:username,discordId,department:'Executive',role:'Owner',supervisor:'None',hireDate:today(),status:'Active',permissionLevel:'System Administrator',pinHash:await hash(pin),createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await seedCourses();await audit('BOOTSTRAP','Owner created and courses seeded.');notice('Owner created. Sign in now.');await checkOwner()}
async function seedCourses(){for(const c of premadeCourses)await setDoc(doc(db,'courses',c.id),{...c,updatedAt:serverTimestamp()},{merge:true})}
function notice(m){$('loginNotice').innerHTML=`<div class="notice">${m}</div>`}
async function login(){const username=$('loginUsername').value.trim(),discordId=$('loginDiscordId').value.trim(),pin=$('loginPin').value.trim();const s=await getDocs(query(collection(db,'employees'),where('discordId','==',discordId),limit(1)));if(s.empty)return notice('No staff account found.');const emp={...s.docs[0].data(),id:s.docs[0].id};if(emp.discordUsername.toLowerCase()!==username.toLowerCase())return notice('Discord username does not match.');if(emp.status!=='Active'&&emp.status!=='Awaiting PIN Setup')return notice('This account is not active.');if(!emp.pinHash){if(!/^[0-9]{4}$/.test(pin))return notice('First login: enter the 4-digit PIN you want to create.');emp.pinHash=await hash(pin);await updateDoc(doc(db,'employees',emp.id),{pinHash:emp.pinHash,status:'Active',updatedAt:serverTimestamp()})}else if(emp.pinHash!==await hash(pin))return notice('Incorrect PIN.');state.user=emp;$('loginScreen').classList.add('hidden');$('app').classList.remove('hidden');await load();shell();render()}
async function load(){for(const k of ['employees','courses','assignments','progress','certifications','attempts']){const s=await getDocs(collection(db,k));state[k]=s.docs.map(d=>({...d.data(),id:d.id}))}}
async function audit(action,details){await addDoc(collection(db,'auditLogs'),{action,details,actor:state.user?.id||'SYSTEM',actorName:state.user?.displayName||'System',at:serverTimestamp()})}
function shell(){$('profileName').textContent=state.user.displayName||state.user.discordUsername;$('profileRole').textContent=state.user.role;$('profileDept').textContent=state.user.department;const items=[['dashboard','Dashboard'],['training','My Training'],['library','Course Library'],['certs','My Certifications'],['monthly','Monthly Training']];if(manager())items.push(['reports','Reports']);if(admin())items.push(['admin','Administration'],['staff','Staff'],['builder','Course Builder'],['assign','Assignment Center']);$('nav').innerHTML=items.map(i=>`<button class="${state.route===i[0]?'active':''}" data-route="${i[0]}">${i[1]}</button>`).join('');document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{state.route=b.dataset.route;shell();render()})}
function page(t,s='',a=''){$('pageTitle').textContent=t;$('pageSub').textContent=s;$('pageActions').innerHTML=a}
const assignments=(e=state.user)=>state.assignments.filter(a=>a.target==='Everyone'||a.employeeId===e.id||a.target===e.department||a.target===e.role);
const done=(cid,eid=state.user.id)=>state.progress.find(p=>p.courseId===cid&&p.employeeId===eid);
function render(){({dashboard,training,library,certs,monthly,reports,adminView,staff,builder,assign}[state.route]||dashboard)()}
function dashboard(){page('Dashboard','Your training command center.');const a=assignments(),d=a.filter(x=>done(x.courseId)).length,o=a.filter(x=>x.dueDate&&x.dueDate<today()&&!done(x.courseId)).length,cert=state.certifications.filter(c=>c.employeeId===state.user.id&&c.status!=='Revoked');$('view').innerHTML=`<div class="hero"><div class="kicker">Cognitus Academy</div><h2>Welcome back, ${esc(state.user.displayName||state.user.discordUsername)}.</h2><p class="muted">Keep training current, maintain certifications, and stay ready for more responsibility.</p></div><div class="grid g4" style="margin-top:18px"><div class="card"><div class="stat">${a.length}</div><b>Assigned</b></div><div class="card"><div class="stat">${d}</div><b>Complete</b></div><div class="card"><div class="stat">${cert.length}</div><b>Certificates</b></div><div class="card"><div class="stat">${o}</div><b>Overdue</b></div></div><div class="grid g2" style="margin-top:18px"><div class="card"><h3>Continue Learning</h3>${a.slice(0,6).map(assignmentRow).join('')||'<div class="empty">No assignments yet.</div>'}</div><div class="card"><h3>Recent Certificates</h3>${cert.slice(0,6).map(c=>`<p>${pill('Active','green')} <b>${esc(c.certificateName)}</b><br><span class="small">Issued ${esc(c.issueDate)}</span></p>`).join('')||'<div class="empty">No certificates yet.</div>'}</div></div>`}
function assignmentRow(a){const c=state.courses.find(x=>x.id===a.courseId)||{},is=done(a.courseId);return`<div class="notice"><div class="row"><div><b>${esc(c.title||a.courseId)}</b><br><span class="small">Due ${esc(a.dueDate||'No due date')} • ${esc(c.estimatedMinutes||'?')} min</span></div>${is?pill('Complete','green'):`<button onclick="openCourse('${a.courseId}')">Start</button>`}</div></div>`}
function card(c,assigned=false){if(!c)return'';const is=done(c.id);return`<div class="card course-card"><div class="row"><span>${pill(c.category,'blue')} ${c.monthly?pill('Monthly','gold'):''}</span>${assigned?(is?pill('Complete','green'):pill('Assigned')):''}</div><div class="grow"><h3>${esc(c.title)}</h3><p class="muted">${esc(c.department)} • ${esc(c.role)} • ${esc(c.difficulty)} • ${esc(c.estimatedMinutes)} min</p><div class="progress"><span style="width:${is?100:0}%"></span></div></div><button class="secondary" onclick="openCourse('${c.id}')">${is?'Review Course':'Start Course'}</button></div>`}
function training(){page('My Training','Required and assigned courses.');$('view').innerHTML=`<div class="grid g2">${assignments().map(a=>card(state.courses.find(c=>c.id===a.courseId),true)).join('')||'<div class="empty">No training assigned yet.</div>'}</div>`}
function library(){page('Course Library','All active Cognitus Academy courses.');$('view').innerHTML=`<div class="grid g3">${state.courses.filter(c=>c.status!=='Archived').map(c=>card(c)).join('')}</div>`}
function certs(){page('My Certifications','Certificates earned through Cognitus Academy.');const rows=state.certifications.filter(c=>c.employeeId===state.user.id);$('view').innerHTML=`<div class="card"><table class="table"><tr><th>Certificate</th><th>Course</th><th>Score</th><th>Issued</th><th>Status</th></tr>${rows.map(c=>`<tr><td><b>${esc(c.certificateName)}</b><br><span class="small">${esc(c.id)}</span></td><td>${esc(c.courseTitle)}</td><td>${esc(c.score)}%</td><td>${esc(c.issueDate)}</td><td>${pill(c.status||'Active',c.status==='Revoked'?'red':'green')}</td></tr>`).join('')||'<tr><td colspan="5">No certifications yet.</td></tr>'}</table></div>`}
function monthly(){page('Monthly Training','Required recurring monthly training.');$('view').innerHTML=`<div class="grid g2">${state.courses.filter(c=>c.monthly).map(c=>card(c)).join('')||'<div class="empty">No monthly courses yet.</div>'}</div>`}
function reports(){if(!manager())return dashboard();page('Reports','Training compliance by employee.');const rows=state.employees.map(e=>{const a=assignments(e),d=a.filter(x=>done(x.courseId,e.id)).length;return{...e,total:a.length,done:d,pct:a.length?Math.round(d/a.length*100):0}});$('view').innerHTML=`<div class="card"><table class="table"><tr><th>Employee</th><th>Department</th><th>Role</th><th>Progress</th><th>Status</th></tr>${rows.map(r=>`<tr><td><b>${esc(r.displayName)}</b><br><span class="small">${esc(r.id)}</span></td><td>${esc(r.department)}</td><td>${esc(r.role)}</td><td><div class="progress"><span style="width:${r.pct}%"></span></div><span class="small">${r.done}/${r.total}</span></td><td>${r.pct===100?pill('Complete','green'):pill('In Progress')}</td></tr>`).join('')}</table></div>`}
function adminView(){if(!admin())return dashboard();page('Administration','Owner and executive controls.');$('view').innerHTML=`<div class="grid g3"><div class="card"><div class="stat">${state.employees.length}</div><b>Employees</b></div><div class="card"><div class="stat">${state.courses.length}</div><b>Courses</b></div><div class="card"><div class="stat">${state.certifications.length}</div><b>Certificates Issued</b></div></div><div class="grid g2" style="margin-top:18px"><button class="card" onclick="go('staff')"><h3>Staff Management</h3><p>Add staff and manage role placement.</p></button><button class="card" onclick="go('builder')"><h3>Course Builder</h3><p>Create lessons, exams, and certificates without JSON.</p></button><button class="card" onclick="go('assign')"><h3>Assignment Center</h3><p>Create and edit assignments.</p></button><button class="card" onclick="seedAgain()"><h3>Seed Premade Courses</h3><p>Restore the expanded premade library.</p></button></div>`}
function staff(){if(!admin())return dashboard();page('Staff','Create and manage LMS staff accounts.','<button onclick="staffForm()">Add Staff</button>');$('view').innerHTML=`<div class="card"><table class="table"><tr><th>Employee</th><th>Discord</th><th>Department</th><th>Role</th><th>Status</th></tr>${state.employees.map(e=>`<tr><td><b>${esc(e.displayName)}</b><br><span class="small">${esc(e.id)}</span></td><td>${esc(e.discordUsername)}<br><span class="small">${esc(e.discordId)}</span></td><td>${esc(e.department)}</td><td>${esc(e.role)}</td><td>${pill(e.status,e.status==='Active'?'green':'gold')}</td></tr>`).join('')}</table></div>`}
function builder(){if(!admin())return dashboard();page('Course Builder','Create document-based training and certification courses.','<button onclick="courseForm()">New Course</button>');$('view').innerHTML=`<div class="card"><table class="table"><tr><th>Course</th><th>Department</th><th>Role</th><th>Passing</th><th>Monthly</th><th></th></tr>${state.courses.map(c=>`<tr><td><b>${esc(c.title)}</b><br><span class="small">${esc(c.id)}</span></td><td>${esc(c.department)}</td><td>${esc(c.role)}</td><td>${esc(c.passingScore)}%</td><td>${c.monthly?'Yes':'No'}</td><td><button class="secondary" onclick="courseForm('${c.id}')">Edit</button></td></tr>`).join('')}</table></div>`}
function assign(){if(!admin())return dashboard();page('Assignment Center','Create and adjust assignments.','<button onclick="assignForm()">Create Assignment</button>');$('view').innerHTML=`<div class="card"><table class="table"><tr><th>Course</th><th>Target</th><th>Due</th><th>Required</th><th></th></tr>${state.assignments.map(a=>{const c=state.courses.find(x=>x.id===a.courseId)||{};return`<tr><td><b>${esc(c.title||a.courseId)}</b></td><td>${esc(a.targetLabel||a.employeeId||a.target)}</td><td>${esc(a.dueDate||'No due date')}</td><td>${a.required?'Yes':'No'}</td><td><button class="secondary" onclick="assignForm('${a.id}')">Edit</button></td></tr>`}).join('')||'<tr><td colspan="5">No assignments yet.</td></tr>'}</table></div>`}
window.go=r=>{state.route=r;shell();render()}; window.seedAgain=async()=>{await seedCourses();await audit('SEED','Premade course library seeded.');await load();render()};
window.staffForm=()=>modal(`<h2>Add Staff</h2><div class="grid g2"><label class="field">Display Name<input id="sfName"></label><label class="field">Employee ID<input id="sfId" value="${uid('EMP')}"></label><label class="field">Discord Username<input id="sfUser"></label><label class="field">Discord User ID<input id="sfDiscord"></label><label class="field">Department<select id="sfDept">${departments.map(d=>`<option>${d}</option>`).join('')}</select></label><label class="field">Role<select id="sfRole">${roles.map(r=>`<option>${r}</option>`).join('')}</select></label><label class="field">Supervisor<input id="sfSup"></label><label class="field">Hire Date<input id="sfHire" type="date" value="${today()}"></label></div><button onclick="saveStaff()">Create Staff</button> <button class="secondary" onclick="closeModal()">Cancel</button>`)
window.saveStaff=async()=>{const id=$('sfId').value.trim();if(!id||!$('sfUser').value.trim()||!$('sfDiscord').value.trim())return alert('Employee ID, username, and Discord ID are required.');await setDoc(doc(db,'employees',id),{displayName:$('sfName').value.trim(),discordUsername:$('sfUser').value.trim(),discordId:$('sfDiscord').value.trim(),department:$('sfDept').value,role:$('sfRole').value,supervisor:$('sfSup').value.trim(),hireDate:$('sfHire').value,status:'Awaiting PIN Setup',permissionLevel:'Employee',createdAt:serverTimestamp(),updatedAt:serverTimestamp()});await audit('CREATE_STAFF',`Created ${id}`);closeModal();await load();render()}
window.courseForm=id=>{const c=state.courses.find(x=>x.id===id)||{id:uid('COURSE'),title:'',category:'Custom',department:'All',role:'All',difficulty:'Beginner',estimatedMinutes:30,passingScore:80,certificateName:'',required:false,monthly:false,lessons:[{title:'Lesson 1',body:''}],questions:[{type:'mc',prompt:'',options:['','','',''],answer:''}]};modal(`<h2>${id?'Edit':'New'} Course</h2><div class="grid g3"><label class="field">Course ID<input id="cfId" value="${esc(c.id)}" ${id?'readonly':''}></label><label class="field">Title<input id="cfTitle" value="${esc(c.title)}"></label><label class="field">Category<input id="cfCat" value="${esc(c.category)}"></label><label class="field">Department<select id="cfDept"><option>All</option>${departments.map(d=>`<option ${c.department===d?'selected':''}>${d}</option>`).join('')}</select></label><label class="field">Role<select id="cfRole"><option>All</option>${roles.map(r=>`<option ${c.role===r?'selected':''}>${r}</option>`).join('')}</select></label><label class="field">Difficulty<select id="cfDiff">${['Beginner','Intermediate','Advanced','Executive'].map(d=>`<option ${c.difficulty===d?'selected':''}>${d}</option>`).join('')}</select></label><label class="field">Minutes<input id="cfMin" type="number" value="${esc(c.estimatedMinutes)}"></label><label class="field">Passing Score<input id="cfPass" type="number" value="${esc(c.passingScore)}"></label><label class="field">Certificate Name<input id="cfCert" value="${esc(c.certificateName)}"></label><label class="field">Required<select id="cfReq"><option ${c.required?'selected':''}>Yes</option><option ${!c.required?'selected':''}>No</option></select></label><label class="field">Monthly<select id="cfMonthly"><option ${c.monthly?'selected':''}>Yes</option><option ${!c.monthly?'selected':''}>No</option></select></label></div><div class="row"><h3>Lesson Pages</h3><button class="secondary" onclick="addLessonBox()">Add Lesson</button></div><div id="lessonEditor"></div><div class="row"><h3>Knowledge Check Questions</h3><button class="secondary" onclick="addQuestionBox()">Add Question</button></div><div id="questionEditor"></div><div class="split-actions"><button onclick="saveCourse()">Save Course</button><button class="secondary" onclick="closeModal()">Cancel</button></div>`);(c.lessons||[]).forEach(l=>addLessonBox(l));(c.questions||[]).forEach(q=>addQuestionBox(q))}
window.addLessonBox=(l={title:'',body:''})=>{const w=document.createElement('div');w.className='builder-box lesson-box';w.innerHTML=`<div class="row"><b>Lesson Page</b><button class="ghost" onclick="this.closest('.lesson-box').remove()">Remove</button></div><label class="field">Lesson Title<input class="lesson-title" value="${esc(l.title)}"></label><label class="field">Lesson Content<textarea class="lesson-body">${esc(l.body)}</textarea></label>`;$('lessonEditor').appendChild(w)}
window.addQuestionBox=(q={type:'mc',prompt:'',options:['','','',''],answer:''})=>{const o=q.options||['','','',''];const w=document.createElement('div');w.className='builder-box question-box';w.innerHTML=`<div class="row"><b>Question</b><button class="ghost" onclick="this.closest('.question-box').remove()">Remove</button></div><label class="field">Type<select class="q-type"><option ${q.type==='mc'?'selected':''} value="mc">Multiple Choice</option><option ${q.type==='tf'?'selected':''} value="tf">True / False</option></select></label><label class="field">Prompt<input class="q-prompt" value="${esc(q.prompt)}"></label><div class="grid g2"><label class="field">Option A<input class="q-opt" value="${esc(o[0]||'')}"></label><label class="field">Option B<input class="q-opt" value="${esc(o[1]||'')}"></label><label class="field">Option C<input class="q-opt" value="${esc(o[2]||'')}"></label><label class="field">Option D<input class="q-opt" value="${esc(o[3]||'')}"></label></div><label class="field">Correct Answer<input class="q-answer" value="${esc(q.answer)}" placeholder="True, False, or exact option text"></label>`;$('questionEditor').appendChild(w)}
window.saveCourse=async()=>{const id=$('cfId').value.trim();const lessons=[...document.querySelectorAll('.lesson-box')].map(b=>({title:b.querySelector('.lesson-title').value.trim(),body:b.querySelector('.lesson-body').value.trim()})).filter(x=>x.title||x.body);const questions=[...document.querySelectorAll('.question-box')].map(b=>{const type=b.querySelector('.q-type').value;return{type,prompt:b.querySelector('.q-prompt').value.trim(),options:type==='tf'?['True','False']:[...b.querySelectorAll('.q-opt')].map(i=>i.value.trim()).filter(Boolean),answer:b.querySelector('.q-answer').value.trim()}}).filter(x=>x.prompt&&x.answer);if(!id||!$('cfTitle').value.trim())return alert('Course ID and title are required.');if(!lessons.length)return alert('Add at least one lesson.');if(!questions.length)return alert('Add at least one question.');await setDoc(doc(db,'courses',id),{title:$('cfTitle').value.trim(),category:$('cfCat').value.trim(),department:$('cfDept').value,role:$('cfRole').value,difficulty:$('cfDiff').value,estimatedMinutes:Number($('cfMin').value),passingScore:Number($('cfPass').value),certificateName:$('cfCert').value.trim(),required:$('cfReq').value==='Yes',monthly:$('cfMonthly').value==='Yes',lessons,questions,status:'Active',createdBy:state.user.id,updatedAt:serverTimestamp()},{merge:true});await audit('SAVE_COURSE',`Saved ${id}`);closeModal();await load();render()}
window.assignForm=id=>{const a=state.assignments.find(x=>x.id===id)||{courseId:'',type:'Everyone',target:'Everyone',employeeId:'',targetLabel:'Everyone',dueDate:'',required:true};modal(`<h2>${id?'Edit':'Create'} Assignment</h2><label class="field">Course<select id="afCourse">${state.courses.map(c=>`<option value="${c.id}" ${a.courseId===c.id?'selected':''}>${esc(c.title)}</option>`).join('')}</select></label><label class="field">Assignment Type<select id="afType"><option ${a.type==='Everyone'?'selected':''}>Everyone</option><option ${a.type==='Employee'?'selected':''}>Employee</option><option ${a.type==='Department'?'selected':''}>Department</option><option ${a.type==='Role'?'selected':''}>Role</option></select></label><label class="field">Target<select id="afTarget"></select></label><label class="field">Due Date<input id="afDue" type="date" value="${esc(a.dueDate)}"></label><label class="field">Required<select id="afReq"><option ${a.required?'selected':''}>Yes</option><option ${!a.required?'selected':''}>No</option></select></label><div class="split-actions"><button onclick="saveAssign('${id||''}')">Save Assignment</button><button class="secondary" onclick="closeModal()">Cancel</button></div>`);const fill=()=>{const t=$('afType').value;let opts=['Everyone'];if(t==='Employee')opts=state.employees.map(e=>`${e.id}|${e.displayName}`);if(t==='Department')opts=departments;if(t==='Role')opts=roles;$('afTarget').innerHTML=opts.map(o=>`<option ${o===`${a.employeeId}|${a.targetLabel}`||o===a.target?'selected':''}>${esc(o)}</option>`).join('')};$('afType').onchange=fill;fill()}
window.saveAssign=async id=>{const type=$('afType').value,raw=$('afTarget').value;let target='Everyone',employeeId='',label='Everyone';if(type==='Employee'){employeeId=raw.split('|')[0];label=raw.split('|')[1];target='Employee'}else if(type!=='Everyone'){target=raw;label=raw}const payload={courseId:$('afCourse').value,type,target,employeeId,targetLabel:label,dueDate:$('afDue').value,required:$('afReq').value==='Yes',updatedBy:state.user.id,updatedAt:serverTimestamp()};if(id)await updateDoc(doc(db,'assignments',id),payload);else await addDoc(collection(db,'assignments'),{...payload,assignedBy:state.user.id,assignedAt:serverTimestamp()});await audit(id?'UPDATE_ASSIGNMENT':'ASSIGN_COURSE',`Saved assignment for ${label}`);closeModal();await load();render()}
window.openCourse=id=>{const c=state.courses.find(x=>x.id===id);if(!c)return;state.player={courseId:id,page:0};modal('<div id="coursePlayer"></div>');renderCoursePage()}
window.stateGoPage=i=>{const c=state.courses.find(x=>x.id===state.player.courseId),total=(c.lessons||[]).length+1;if(i<0||i>=total)return;state.player.page=i;renderCoursePage()}
function renderCoursePage(){const c=state.courses.find(x=>x.id===state.player.courseId);const pages=[...(c.lessons||[]).map((l,i)=>({...l,type:'lesson',label:`Lesson ${i+1}`})),{type:'exam',title:'Final Knowledge Check',label:'Exam'}],p=pages[state.player.page];const menu=pages.map((x,i)=>`<button class="${i===state.player.page?'active':''}" onclick="stateGoPage(${i})">${esc(x.label)}<br><span class="small">${esc(x.title)}</span></button>`).join('');const body=p.type==='lesson'?`<div class="card lesson-card"><div class="kicker">${esc(p.label)}</div><h2>${esc(p.title)}</h2><div class="lesson">${esc(p.body)}</div></div>`:`<div class="card"><div class="kicker">Assessment</div><h2>Final Knowledge Check</h2><p class="muted">Passing score: ${esc(c.passingScore)}%.</p>${(c.questions||[]).map((q,i)=>`<div class="question"><b>${i+1}. ${esc(q.prompt)}</b>${(q.type==='tf'?['True','False']:(q.options||[])).map(o=>`<label class="answer"><input type="radio" name="q${i}" value="${esc(o)}"> ${esc(o)}</label>`).join('')}</div>`).join('')}<label class="answer"><input id="ack" type="checkbox"> I certify I have read and understand this course material.</label></div>`;$('coursePlayer').innerHTML=`<div class="course-shell"><div class="course-menu"><h3>${esc(c.title)}</h3><p class="small">${esc(c.department)} • ${esc(c.estimatedMinutes)} min</p>${menu}</div><div><div class="row" style="margin-bottom:14px">${pill(c.category,'blue')} ${c.monthly?pill('Monthly','gold'):''} ${done(c.id)?pill('Completed','green'):''}</div>${body}<div class="split-actions"><button class="secondary" ${state.player.page===0?'disabled':''} onclick="stateGoPage(${state.player.page-1})">Previous</button><div class="small">Page ${state.player.page+1} of ${pages.length}</div>${p.type==='exam'?`<button onclick="submitCourse('${c.id}')">Submit Course</button>`:`<button onclick="stateGoPage(${state.player.page+1})">Next</button>`}</div></div></div>`}
window.submitCourse=async id=>{const c=state.courses.find(x=>x.id===id);if(!$('ack')?.checked)return alert('You must acknowledge the course material.');let correct=0,total=(c.questions||[]).length;(c.questions||[]).forEach((q,i)=>{const chosen=document.querySelector(`input[name="q${i}"]:checked`)?.value;if(String(chosen).trim()===String(q.answer).trim())correct++});const score=total?Math.round(correct/total*100):100,passed=score>=Number(c.passingScore||80);await addDoc(collection(db,'attempts'),{employeeId:state.user.id,courseId:id,score,passed,correct,total,at:serverTimestamp()});if(passed){await setDoc(doc(db,'progress',`${state.user.id}_${id}`),{employeeId:state.user.id,courseId:id,courseTitle:c.title,completedAt:today(),score,status:'Complete'},{merge:true});const certId=uid('CERT');await setDoc(doc(db,'certifications',certId),{employeeId:state.user.id,courseId:id,courseTitle:c.title,certificateName:c.certificateName||`${c.title} Completion`,score,issueDate:today(),status:'Active'});await audit('COURSE_COMPLETE',`${state.user.id} completed ${id} with ${score}%`);alert(`Passed with ${score}%. Certificate issued.`)}else alert(`Score: ${score}%. Passing score is ${c.passingScore}%. Please review and try again.`);closeModal();await load();render()}
init();
